@extends('layouts.admin.app')

@section('title', translate('Invoice'))

@push('css_or_js')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" src="{{ asset('public/assets/admin') }}/vendor/apex/apexcharts.css">
    </link>
@endpush

@section('content')
    <div class="content container-fluid">
        <div class="d-flex justify-content-between items-center">
            <div class=" bg-white">

                <ul class="nav nav-pills mb-3 border" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">

                        <a href="{{ route('admin.invoice_index') }}" class="nav-link {{ request()->has("param") ? '' : 'active' }}">All invoices</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="{{ route('admin.invoice_index',["param"=>'due']) }}" class="nav-link {{ request()->get("param") == 'due' ? 'active' : '' }}">Due date invoices</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="{{ route('admin.invoice_index',["param"=>1]) }}" class="nav-link {{ request()->get("param") == '1' ? 'active' : '' }}">Paid</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="{{ route('admin.invoice_index',["param"=>3]) }}" class="nav-link {{ request()->get("param") == '3' ? 'active' : '' }}">Partially paid</a>
                    </li>
                </ul>
            </div>


        </div>

        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Invoice Number</th>
                <th scope="col">Generated By</th>

                <th scope="col">Amount</th>
                <th scope="col">Due Date</th>
                <th scope="col">Status</th>

                <th scope="col">Action</th>

              </tr>
            </thead>
            <tbody>
                @if(!empty($invoices))
                @foreach ($invoices as $index=>$invoice)

                <tr>
                    <th scope="row">{{$index + 1}}</th>
                    <td>{{$invoice->invoice_number}}</td>
                    <td>{{$invoice?->vendor?->first_name.' '.$invoice?->vendor?->last_name}}</td>

                    <td>{{$invoice->amount}}</td>
                    <td>{{\Carbon\Carbon::parse($invoice->due_date)->format('M d,Y')}}</td>
                    <td>
                        <span class="{{$invoice->status == 1 ? 'bg-success' : ($invoice->status == 3 ? 'bg-warning': 'bg-danger')}} p-2 rounded text-white">{{$invoice->status == 1 ? 'Paid' : ($invoice->status == 3 ? 'Patially Paid': 'Un Paid')}}</span>
                        </td>

                    <td>
                        {{-- <a target="_blank" class="border p-2 btn btn-info" href="{{asset("/public/storage/".$invoice->upload_pdf)}}"><i>View Pdf</i></a> --}}
                        <a href="{{ route('admin.invoice_viewInvoice',["id"=>$invoice->id]) }}" class="border p-2 btn btn-primary"><i>View</i></a>

                    </td>
                </tr>
                  @endforeach
                @endif
            </tbody>
          </table>
{{$invoices->links()}}
    </div>



@endsection

